import { NextRequest, NextResponse } from "next/server";
import { createSupabaseServer } from "@/lib/supabase/server";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import crypto from "node:crypto";

const TOKEN_EXPIRY_DAYS = 14;
const TOKEN_MAX_USES = 10;

// Reason: 32-char URL-safe base64. Matches the format of collection_link_token
// generated by the SQL function in 20241009_add_collection_tokens.sql.
function generateToken(): string {
  return crypto.randomBytes(24).toString("base64url");
}

function expiresAtFromNow(): string {
  const d = new Date();
  d.setDate(d.getDate() + TOKEN_EXPIRY_DAYS);
  return d.toISOString();
}

// Reason: any group member (organizer or captain) can read/regenerate the
// captain invite token. Captains often need to bring in more captains; the
// only restriction is that you must already belong to the group.
//
// Note: identity check uses the user-session client (RLS enforced), but the
// membership lookup uses the admin client so we don't get false negatives
// from RLS policies that hide a user's own group_members row.
async function verifyGroupAccess(groupId: string): Promise<
  { ok: true; userId: string } | { ok: false; status: number; error: string }
> {
  const supabase = await createSupabaseServer();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return { ok: false, status: 401, error: "Unauthorized" };

  const supabaseAdmin = createSupabaseAdminClient();

  // Primary check: are they in group_members?
  // Reason: group_members has a composite PK (group_id, profile_id) — no `id`
  // column. Select profile_id to verify the row exists.
  const { data: membership } = await supabaseAdmin
    .from("group_members")
    .select("profile_id")
    .eq("group_id", groupId)
    .eq("profile_id", user.id)
    .maybeSingle();
  if (membership) return { ok: true, userId: user.id };

  // Fallback: the group creator is implicitly authorized even if for some
  // reason they're not listed in group_members.
  const { data: group } = await supabaseAdmin
    .from("groups")
    .select("created_by")
    .eq("id", groupId)
    .single();
  if (!group) return { ok: false, status: 404, error: "Group not found" };
  if (group.created_by === user.id) return { ok: true, userId: user.id };

  return { ok: false, status: 403, error: "You're not a member of this group" };
}

export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ groupId: string }> }
) {
  const { groupId } = await params;
  const check = await verifyGroupAccess(groupId);
  if (!check.ok) return NextResponse.json({ error: check.error }, { status: check.status });

  const supabaseAdmin = createSupabaseAdminClient();
  const { data: g, error: gErr } = await supabaseAdmin
    .from("groups")
    .select("captain_invite_token, captain_invite_token_expires_at, captain_invite_token_max_uses, captain_invite_token_uses")
    .eq("id", groupId)
    .single();

  if (gErr || !g) return NextResponse.json({ error: "Group not found" }, { status: 404 });

  const isExpired = g.captain_invite_token_expires_at
    ? new Date(g.captain_invite_token_expires_at).getTime() < Date.now()
    : true;

  // Reason: lazy-generate on first GET, or when the existing token is expired.
  // Uses COALESCE-style guard so two concurrent GETs racing each other don't
  // produce two different tokens — the second caller reads the first's value.
  if (!g.captain_invite_token || isExpired) {
    const newToken = generateToken();
    const newExpiresAt = expiresAtFromNow();

    const { data: updated, error: updErr } = await supabaseAdmin
      .from("groups")
      .update({
        captain_invite_token: newToken,
        captain_invite_token_expires_at: newExpiresAt,
        captain_invite_token_max_uses: TOKEN_MAX_USES,
        captain_invite_token_uses: 0,
      })
      .eq("id", groupId)
      .select("captain_invite_token, captain_invite_token_expires_at, captain_invite_token_max_uses, captain_invite_token_uses")
      .single();

    if (updErr || !updated) {
      return NextResponse.json({ error: "Could not generate captain link" }, { status: 500 });
    }

    return NextResponse.json({
      token: updated.captain_invite_token,
      expires_at: updated.captain_invite_token_expires_at,
      max_uses: updated.captain_invite_token_max_uses,
      uses: updated.captain_invite_token_uses,
    });
  }

  return NextResponse.json({
    token: g.captain_invite_token,
    expires_at: g.captain_invite_token_expires_at,
    max_uses: g.captain_invite_token_max_uses,
    uses: g.captain_invite_token_uses,
  });
}

export async function POST(
  _request: NextRequest,
  { params }: { params: Promise<{ groupId: string }> }
) {
  const { groupId } = await params;
  const check = await verifyGroupAccess(groupId);
  if (!check.ok) return NextResponse.json({ error: check.error }, { status: check.status });

  const supabaseAdmin = createSupabaseAdminClient();
  const newToken = generateToken();
  const newExpiresAt = expiresAtFromNow();

  const { data: updated, error: updErr } = await supabaseAdmin
    .from("groups")
    .update({
      captain_invite_token: newToken,
      captain_invite_token_expires_at: newExpiresAt,
      captain_invite_token_max_uses: TOKEN_MAX_USES,
      captain_invite_token_uses: 0,
    })
    .eq("id", groupId)
    .select("captain_invite_token, captain_invite_token_expires_at, captain_invite_token_max_uses, captain_invite_token_uses")
    .single();

  if (updErr || !updated) {
    return NextResponse.json({ error: "Could not regenerate captain link" }, { status: 500 });
  }

  return NextResponse.json({
    token: updated.captain_invite_token,
    expires_at: updated.captain_invite_token_expires_at,
    max_uses: updated.captain_invite_token_max_uses,
    uses: updated.captain_invite_token_uses,
  });
}
