-- Create midjourney_prompts table for storing AI-generated prompts for recipes
CREATE TABLE IF NOT EXISTS public.midjourney_prompts (
  -- Primary key
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  
  -- Foreign key to recipe
  recipe_id UUID NOT NULL REFERENCES public.guest_recipes(id) ON DELETE CASCADE,
  
  -- The generated Midjourney prompt (most important field)
  generated_prompt TEXT NOT NULL,
  
  -- Complete agent metadata stored as JSONB for flexibility
  -- This includes: date, generator, token_count, style, original_dish_name,
  -- AI_dish_identification, recipe, AI_learning_summary, AI_decision_framework, etc.
  agent_metadata JSONB,
  
  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  
  -- Constraints
  CONSTRAINT unique_recipe_prompt UNIQUE(recipe_id)
);

-- Add comments to midjourney_prompts table
COMMENT ON TABLE public.midjourney_prompts IS 'AI-generated Midjourney prompts for recipe images. Stores the generated prompt text and complete agent metadata for analysis and debugging.';
COMMENT ON COLUMN public.midjourney_prompts.id IS 'Unique identifier for the prompt record';
COMMENT ON COLUMN public.midjourney_prompts.recipe_id IS 'Reference to the recipe this prompt was generated for. One prompt per recipe.';
COMMENT ON COLUMN public.midjourney_prompts.generated_prompt IS 'The final Midjourney prompt text generated by the AI agent. This is the primary output used for image generation.';
COMMENT ON COLUMN public.midjourney_prompts.agent_metadata IS 'Complete metadata from the AI agent stored as JSONB. Includes generation date, token count, style, dish identification, learning patterns, decision framework, and all other agent output data.';
COMMENT ON COLUMN public.midjourney_prompts.created_at IS 'Timestamp when the prompt was first generated';
COMMENT ON COLUMN public.midjourney_prompts.updated_at IS 'Timestamp when the prompt was last updated (if regenerated)';

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_midjourney_prompts_recipe_id ON public.midjourney_prompts(recipe_id);
CREATE INDEX IF NOT EXISTS idx_midjourney_prompts_created_at ON public.midjourney_prompts(created_at);

-- Enable Row Level Security
ALTER TABLE public.midjourney_prompts ENABLE ROW LEVEL SECURITY;

-- RLS Policies for midjourney_prompts table
-- Users can view prompts for recipes they own (through guest_recipes.user_id)
CREATE POLICY "Users can view prompts for own recipes" 
  ON public.midjourney_prompts 
  FOR SELECT 
  USING (
    recipe_id IN (
      SELECT id FROM public.guest_recipes 
      WHERE user_id = auth.uid()
    )
  );

-- Users can insert prompts for recipes they own
CREATE POLICY "Users can insert prompts for own recipes" 
  ON public.midjourney_prompts 
  FOR INSERT 
  WITH CHECK (
    recipe_id IN (
      SELECT id FROM public.guest_recipes 
      WHERE user_id = auth.uid()
    )
  );

-- Users can update prompts for recipes they own
CREATE POLICY "Users can update prompts for own recipes" 
  ON public.midjourney_prompts 
  FOR UPDATE 
  USING (
    recipe_id IN (
      SELECT id FROM public.guest_recipes 
      WHERE user_id = auth.uid()
    )
  )
  WITH CHECK (
    recipe_id IN (
      SELECT id FROM public.guest_recipes 
      WHERE user_id = auth.uid()
    )
  );

-- Users can delete prompts for recipes they own (useful for regeneration)
CREATE POLICY "Users can delete prompts for own recipes" 
  ON public.midjourney_prompts 
  FOR DELETE 
  USING (
    recipe_id IN (
      SELECT id FROM public.guest_recipes 
      WHERE user_id = auth.uid()
    )
  );

